name: recruiting
description: Launchpad Studios Recruiting Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  google_fonts: ^2.0.0
  intl: ^0.17.0
  responsive_builder: ^0.4.0-nullsafety.1
  tailwind_colors: ^0.3.0-nullsafety.1
  timeago: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/